### ISSUE TITLE
How to do two-way data-binding with actions and getters ? (e.g. for textfields)

### ISSUE THREAD

**Issue by major-mayer** [damianof/large-scale-apps-my-svelte-project#3]
_Note: I've originally written this as an e-mail, but, as I've not received a response yet, I am reposting this here for increased visibility._

Hi Damiano,
I have recently bought your book "Large Scale Apps with Svelte and TypeScript" and really like the concepts that you bring up to create Svelte apps that scale.
My focus lies especially on the topic "State Management".

I like the introduction of actions and setters to the Svelte stores, because i already know them from VueJs / Vuex.
But i have one question in mind that i wasn't able to solve:
What should I do, if i have text fields that should be bound to the svelte store to show the current value, but also should be able to update the store's value?

I understood that every update should go through an action and this is great, because I can then directly bundle it with sending the updated value to the backend server.
While this works great for simple buttons (like in your example the Item component that can be clicked) or when the initial value is irrelevant (like in the LocaleSelector where you bind the input field to the local variable "currentLocale" that is by default set to an empty string), in my case I need a two-way between a store's value and a text input.

This means that initially the text field should show whatever is in the store right now, but when the user changes its value, it should also be able to update the value.
But of course not directly, but through an action that is able to send the value to the API endpoint and maybe does some frontend form validation.

I was thinking about creating local (component) variables for this, loading the value from the store with the onMount() hook and adding a submit button, that more-or-less copies the values from the component to the actual store using an action.
But this means that if the store's value was updated after the initial load and not from the component itself, the change would not be displayed correctly.

In VueJS, I would probably use some kind of computed property for this: https://docs.gitlab.com/ee/development/fe_guide/vuex.html#two-way-data-binding
But as this is not an option in Svelte, how would you handle such a case?

Best wishes
Laurenz

**Comment by damianof** [comment]
Did you try starting here:

https://svelte.dev/repl/9f48844e524b4b97a3865453437edc07?version=3.20.1

https://svelte.dev/repl/e6f91174592d45c78f4701b2d311b62e?version=3.29.4

There you should get hints on how to implement with a modular store. Note that there are multiple ways to do this.

**Comment by major-mayer** [comment]
Your examples weren't exactly what I was looking for, but still they provided a starting point, so thank you.
I was finally able to find a solution that I can use with getters and actions.
I am now using a temporary variable that mirrors the getter's value and the on:input event to write new values directly to the store.
Have a look here, maybe you can spot some improvements:
https://svelte.dev/repl/430f15cd800c49cdbce2eb7346cfc960?version=3.29.4

**Comment by damianof** [comment]
So there are different school of thoughts, or better, different approaches. They all have pros and cons. I can think of at least 2 or even 3.

One approach, is when a field value is bound directly to the model value so any change you make it is immediately applied to the model value. I.e. customer.name with a value of "John" bound to a textbox. As you start typing the value changes, i.e. "Mary". Now your model has a pending change, and if you need other state to be aware of that, you would have to track it in some way. This is what usually form components libraries do, as it the only way for them to create reusable components without too much complexity.

Another approach is either a two-way binding but with a local state (not your original model). This has a lot of advantages, but requires more plumbing code. First you need to pass your model to your component as a property, within the component copy that value to an internal state variable, two-way bind the internal state to the field. Now as you change the value, the internal state value i s updated, but not the original model that was passed as a property. This give you a change to do some validation for example (i.e. value should be only numeric) before emitting an event with the valid value to the parent or external state to eventually update the original model. You can also always emit the change and let the parent or external state module handle additional logici, i.e. validation etc. It all depends on what you need to do. 

A 3rd approach similar to the 2nd one above, is to not even have an internal state in the component, and use one-way binding. Then emit the changes and let the parent/external state handle any logic and final mutation to the state. This is very similar to the 2nd approach, and in some cases makes sense, while in others the 2nd might offer more benefits.

**Comment by major-mayer** [comment]
Hi @damianof ,
thanks for your very informative input.
I think i will go with the second approach, as I see the benefits from doing the form validation and so on.
The only thing I'm not clear yet, is when to do the final mutation in the store, but this will most likely depend heavily on the actual use case.

In my case I need to transfer the values to the backend server, so it will most likely be way to much load for the server to update the value on each input event.
I think I will go with some kind of throttling or simply use a submit button.
